# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='counteudo',
        ),
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default='', verbose_name='Conte\xfado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de cria\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=1024, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio'),
        ),
    ]
